### ISSUE TITLE
issue is response result = please try later every time.

### ISSUE THREAD

**Issue by jarvisx17** [DashyDashOrg/pandas-llm#6]
it's not working from today. I've been using it for a month but from today it keeps responding to me please try later. please help me with the error @muhammad-abdullah-dashy-dash @alessiodashydash @alessioricco @kairavdashydash

**Comment by alessioricco** [comment]
Hi @jarvisx17 
I tried it locally and I noticed that the examples are currently working.
Could you please tell me more about the issue you are having, maybe a the slice of code you're using?

**Comment by LeoLy77** [comment]
Hi, below is the error log, seems like the call is depreciated

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.
